export const mockData = {
  materials: {
    data: [
      {
        id: "1",
        title: "Процесс обучения и развития в Компании",
        link: "home",
      },
      {
        id: "2",
        title: "Важные материалы",
        link: "home2",
      },
    ],
    error: false,
    errorText: "",
  },
  recommendations: {
    data: [
      {
        id: "1",
        title: "Рекомендации по обучению",
        text: "Мы собрали для вас лучшие рекомендации для старта!",
        image: "",
        link: "фывфы",
        link_target: "",
        buttonName: "Узнай свой уровень",
      },
      {
        id: "2",
        title: "Тест по профориентации",
        text: "Вы можете знааааачительно больше, чем может казаться!",
        image:
          "https://i.pinimg.com/originals/5d/e2/42/5de24294bad21ec99931f4c362354f22.jpg",
        link: "/home",
        link_target: "",
        buttonName: "Перейти",
      },
      {
        id: "3",
        title: "Истории повышения",
        text: "Вдохновляйся опытом своих коллег!",
        image:
          "https://i.pinimg.com/originals/5d/e2/42/5de24294bad21ec99931f4c362354f22.jpg",
        link: "/home",
        link_target: "",
        buttonName: "Перейти",
      },
      {
        id: "4",
        title: "Лайфхаки",
        text: "Гуру делятся своим опытом!",
        image: "",
        link: "",
        link_target: "",
        buttonName: "Перейти",
      },
      {
        id: "5",
        title: "Записи конференций",
        text: "Для тех, кто не успел посмотреть живьем.",
        image: "",
        link: "/home",
        link_target: "",
        buttonName: "Перейти",
      },
      {
        id: "6",
        title: "Каталог рекомендованных курсов по обучению",
        text: "Тут вы найдете все и даже больше!",
        image:
          "https://i.pinimg.com/originals/5d/e2/42/5de24294bad21ec99931f4c362354f22.jpg",
        link: "/home",
        link_target: "",
        buttonName: "Перейти",
      },
      {
        id: "7",
        title: "Самодиагностика",
        text: "Лучше, чем ваш лечащий врач!",
        image: "",
        link: "",
        link_target: "",
        buttonName: "Перейти",
      },
      {
        id: "8",
        title: "Самодиагностика",
        text: "Лучше, чем ваш лечащий врач!",
        image: "",
        link: "",
        link_target: "",
        buttonName: "Перейти",
      },
      {
        id: "9",
        title: "Самодиагностика",
        text: "Лучше, чем ваш лечащий врач!",
        image: "",
        link: "",
        link_target: "",
        buttonName: "Перейти",
      },
    ],
    error: false,
    errorText: "",
  },
  userInfo: {
    data: {
      fullname: "Алексеев Кирилл Владимирович",
      position: "Разработчик-эксперт",
      avatar:
        "https://i.pinimg.com/736x/d0/cf/a8/d0cfa8b3f2b9aa687e99cdd88bb82f10.jpg",
    },
    error: false,
    errorText: "",
  },
  userActivities: {
    data: [
      {
        icon: "increase",
        title: "Рост (ОС 360)",
        link: "/home",
        date: "24.11.2024",
        status: "Оценка руководителя проводилась очень давно",
        buttonName: "Результаты",
        isAssignable: false,
        progress: {
          type: "score",
          score: "4.7",
          maxScore: "500",
          text: "",
        },
      },
      {
        icon: "assessment_achievements",
        title:
          "Оценка достижений Оценка достижений Оценка достижений Оценка достижений ",
        link: "/home",
        date: "01.01.2020",
        status:
          "asdasd asd as assd asd ad asd asd asd asd adasd asds asdasd asd as assd asd ad asd asd asd asd adasd asds",
        buttonName: "Результаты",
        isAssignable: false,
        progress: {
          type: "text",
          score: "",
          maxScore: "",
          text: "asdasdsad",
        },
      },
      {
        icon: "tech_review",
        title: "Техревью",
        link: "/home",
        date: "23.10.2024",
        status: "Оценка эксперта",
        buttonName: "Результаты",
        isAssignable: false,
        progress: {
          type: "text",
          score: "",
          maxScore: "",
          text: "Middle Senior Expert",
        },
      },
      {
        icon: "career",
        title: "Карьера",
        link: "/home",
        date: "24.11.2024",
        status: "Оценка не проводилась уже слишком давно",
        buttonName: "Начать",
        isAssignable: false,
        progress: {
          type: "text",
          score: "",
          maxScore: "",
          text: "",
        },
      },
      {
        icon: "ipr",
        title: "ИПР Алексеева Кирилла Владимировича апрель 2025",
        link: "/home",
        date: "01.12.2024",
        status: "Оценка завершена",
        buttonName: "Продолжить",
        isAssignable: false,
        progress: {
          type: "progress",
          score: "60",
          maxScore: "100",
          text: "",
        },
      },
      {
        icon: "ipr",
        title: "ИПР",
        link: "",
        date: "",
        status: "",
        buttonName: "Начать",
        isAssignable: true,
        progress: {
          type: "text",
          score: "",
          maxScore: "",
          text: "",
        },
      },
    ],
    error: false,
    errorText: "",
  },
  createIpr: {
    data: {
      icon: "ipr",
      title: "ИПР Алексеева Кирилла Владимировича май 2025",
      link: "/home",
      date: "",
      status: "",
      buttonName: "Продолжить",
      isAssignable: false,
      progress: {
        type: "progress",
        score: "0",
        maxScore: "100",
        text: "",
      },
    },
    error: false,
    errorText: "",
  },
};
